db:
  type: mysql
  ip: 127.0.0.1
  port: 3306
  username: root
  password: 123456Ab
  database: frostmourne_test

log:
  timestampFormat: 2006-01-02.15:04:05.000000
  level: debug

smpp:
  address: 127.0.0.1
  port: 2785

amqp:
  host: 127.0.0.1
  port: 5672
  username: guest
  password: guest